<dec f='include/c++/11/bits/exception_ptr.h' l='76' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<dec f='include/c++/11/bits/exception_ptr.h' l='98' type='void std::rethrow_exception(std::__exception_ptr::exception_ptr )'/>
<use f='include/c++/11/bits/nested_exception.h' l='70' u='c' c='_ZNKSt16nested_exception14rethrow_nestedEv'/>
<doc f='include/c++/11/bits/exception_ptr.h' l='75'>/// Throw the object pointed to by the exception_ptr.</doc>
