<dec f='include/c++/11/bits/exception_ptr.h' l='70' type='std::__exception_ptr::exception_ptr std::current_exception()'/>
<dec f='include/c++/11/bits/exception_ptr.h' l='97' type='std::__exception_ptr::exception_ptr std::current_exception()'/>
<use f='include/c++/11/bits/exception_ptr.h' l='248' u='c' c='_ZSt18make_exception_ptrT_'/>
<use f='include/c++/11/bits/nested_exception.h' l='57' u='c' c='_ZNSt16nested_exceptionC1Ev'/>
<doc f='include/c++/11/bits/exception_ptr.h' l='66'>/** Obtain an exception_ptr to the currently handled exception. If there
   *  is none, or the currently handled exception is foreign, return the null
   *  value.
   */</doc>
